### PR TITLE
Remove trait bounds from struct definitions

### PR DESCRIPTION
**Pull request by thomaseizinger**
Trait bounds only add value if the usage of the type parameters use the functionality that is abstracted over by the trait. This is usually not the case in struct definitions, which is why we can omit the trait bounds here.

I think the trait bounds could also be removed in some other places like `From` conversions or `impl` Blocks that don' use the functionality provided by the `Render` trait. If you are in for that, I'd change those places as well.

### CODE REVIEW

**Comment by csharad** [comment]
@thomaseizinger Thanks for the PR. I am all up for cleaning up useless bloat. 

> If you are in for that, I'd change those places as well.

Yeah! why not?

**Comment by thomaseizinger** [comment]
There is one thing that might be worth considering:

It is a quite easy-to-remember rule that `struct`s usually don't need to have trait bounds.

For `impl` blocks, one might be surprised that certain trait bounds are not there.

I'll see how many I can remove :)

**Comment by thomaseizinger** [comment]
@csharad I removed some more trait bounds from structs, trivial `impl` blocks and `From` conversions.

I kept them in other places because even if they could be removed right now (for example in `FromEventProps`). I think this trait should actually only be available for types that are `Render`.

**Comment by csharad** [comment]
@thomaseizinger You can remove the `RCTX` trait bounds from `FromEventProps` trait as the trait bounds are put in its implementations.

**Review by pepsighan — CHANGES_REQUESTED** [review]

**Comment by csharad** [comment]
Thanks for the PR again.

**Pull request merged**
